"""Add mask_png_base64 to ImageAnnotation

Revision ID: 0bd71db2793a
Revises: 1b9890fdb894
Create Date: 2025-07-24 23:47:55.533779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd71db2793a'
down_revision = '1b9890fdb894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mask_png_base64', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_annotation', schema=None) as batch_op:
        batch_op.drop_column('mask_png_base64')

    # ### end Alembic commands ###
