"""Add ImageAnnotation model

Revision ID: 1b9890fdb894
Revises: 2898f7f4efc6
Create Date: 2025-07-24 21:21:37.508475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9890fdb894'
down_revision = '2898f7f4efc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('criterion', sa.String(length=128), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('bounding_box_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['work_submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_annotation')
    # ### end Alembic commands ###
