"""Add rubric_type to Rubric model

Revision ID: 2898f7f4efc6
Revises: f7416ba2cb1f
Create Date: 2025-07-24 21:17:59.421584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2898f7f4efc6'
down_revision = 'f7416ba2cb1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rubric', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rubric_type', sa.String(length=32), nullable=False, server_default='text'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rubric', schema=None) as batch_op:
        batch_op.drop_column('rubric_type')
    # ### end Alembic commands ###
