"""Add cache_dir to WorkSubmission

Revision ID: b22f97e88373
Revises: faff219573ea
Create Date: 2025-07-24 00:11:40.114262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22f97e88373'
down_revision = 'faff219573ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cache_dir', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_submission', schema=None) as batch_op:
        batch_op.drop_column('cache_dir')

    # ### end Alembic commands ###
